### ISSUE TITLE
Won't compile in Platform I/O under Linux

### ISSUE THREAD

**Issue by buteomont** [CybDis/Lilygo-T5-4.7-WeatherStation-with-HomeAssistant#3]
There are several errors that prevent this code from compiling in _Platform I/O_ under _Linux_ (specifically _PIO 6.1.5_ and _Ubuntu 20.04_).

The first error encountered is in **OWM_EPD47.ino** on lines **59** through **63** where it tries to include the fonts.  The filenames in the code are in camel case, whereas the files themselves are all lowercase. Changing the include statements to all lowercase fixes this problem.

The other errors seem to be caused by actual coding errors on lines **229** in that file and on lines **53** and **61** of **VariantRefBase.hpp**,  as seen in the screenshot below. It seems that the author is trying to call _as()_ to convert the argument to a character pointer, whereas that function was removed from **jsonvariant** in **version 6.20** (see https://arduinojson.org/v6/api/jsonvariant/as/).  Prepending _const_ to _char*_ in line 229 at column 75 seems to fix these problems.
![Screenshot from 2023-01-23 06-46-38](https://user-images.githubusercontent.com/1907543/214034429-b8d1eb0c-dfc5-4329-9783-5e67498c512a.png)

**Comment by heyitsyang** [comment]
It won't compile if you are using Arduino Json 6.20.  You need to use the previous version 6.19.

You should also apply the changes in issue #1 or you will have symptoms described in issue #2

**Comment by CybDis** [comment]
I've updated the names to work with linux.
